# Generated by Django 2.2 on 2019-04-13 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('sname', models.CharField(max_length=20)),
                ('cover', models.FileField(upload_to='')),
                ('bio', models.CharField(max_length=50)),
                ('area_raised', models.CharField(max_length=50)),
                ('primary_sch', models.CharField(max_length=50)),
                ('high_sch', models.CharField(max_length=50)),
                ('campus', models.CharField(blank=True, max_length=50)),
                ('course', models.CharField(blank=True, max_length=50)),
                ('hobby', models.CharField(max_length=50)),
                ('year_joined_library', models.CharField(max_length=4)),
                ('profession', models.CharField(blank=True, max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
